apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-nginx
  namespace: hello-world   # Optional, specify a namespace if needed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world-container
        image: rajus098/hello-world-ngin:v1
        ports:
        - containerPort: 80
