apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: hello-world  # Optional, specify a namespace if needed
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
