name: Deploy to VM

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up SSH agent
        uses: peaceiris/actions-ssh-key-action@v2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_host: 34.29.202.219
          ssh_user: ubuntu

      - name: Add SSH key to the agent
        run: |
          ssh-add -k ~/.ssh/id_rsa

      - name: SSH to VM and execute commands
        run: |
          ssh -T ubuntu@34.29.202.219 '
            cd /home/ubuntu/
            mkdir new_directory
           mkdir -p test
          '
