name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Create kubeconfig from secret
        run: |
          sudo chmod 0644 /etc/environment 
          echo "${{ secrets.KUBECONFIG_DATA }}" > /etc/environment  # Save kubeconfig secret to the config file

      - name: Export KUBECONFIG and Apply Kubernetes Manifests
        run: |
          export KUBECONFIG=/etc/rancher/k3s/k3s.yaml  # Set KUBECONFIG to the path of the generated config file

      - name: Apply Kubernetes manifest
        run: kubectl apply -f hello-world-nginx.yaml
