name: Deploy to VM

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: rajus098/hello-world-ngin:${{ github.sha }}
          dockerfile: ./Dockerfile  # Specify the path to your Dockerfile
          # If you need to authenticate to a private registry:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  deploy-to-VM:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - uses: actions/checkout@v3
      - uses: webh0sted/setup-ssh-agent@v2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: ssh -T ubuntu@34.44.154.198 'docker pull rajus098/hello-world-ngin:${{ github.sha }} && docker run -d -p 8080:80 rajus098/hello-world-ngin:${{ github.sha }}'
