name: Deploy to K3s

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug Working Directory
      run: |
        echo "Current directory: $PWD"
        ls -al

         mkdir ~/.kube
        echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ~/.kube/config
        cat ~/.kube/config
    - name: try to use kubeconfig
      run: kubectl get ns
