name: k3s Testing

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Docker Daemon
        run: docker version
      - uses: debianmaster/actions-k3s@master
        id: k3s
        with:
          version: 'v1.30.6+k3s1'
      - run: |
          kubectl get nodes
