name: Deploy to K3s

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up kubectl
        run: |
          echo "${{ secrets.KUBECONFIG_BASE64 }}" > kubeconfig
          chmod 600 kubeconfig
          export KUBECONFIG=./kubeconfig

      - name: Deploy to K3s
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl create namespace hello-world
          kubectl get pods -n hello-world
          kubectl get svc -n hello-world
